version: '3.9'

services:
  postgres:
    container_name: postgres-container
    image: postgres:14.5-alpine

    user: postgres
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: projeto-labbd
      POSTGRES_PORT: '5432' 
    
    volumes:
      - postgres:/var/lib/postgres/data

    expose:
      - "5432" 

    healthcheck:
       test: [ "CMD", "pg_isready"]
       interval: 10s
       timeout: 5s
       retries: 5 

    networks:
      - postgres-relatorio
  
  rust-relatorio:
    container_name: backend-rust-relatorio
    image: giovannaopus/backend-rust:1.0
    
    environment:
      ROCKET_ADDRESS: '0.0.0.0'
      ROCKET_PORT: 8080
      ROCKET_DATABASES: '{database={url="postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres/projeto-labbd"}}'
      ROCKET_SECRET_KEY: ${SECRET_KEY}
      ROCKET_LOG_LEVEL: 'debug'

    depends_on:
      - db_init

    ports:
      - "8001:8080"
    
    networks:
      - postgres-relatorio

  db_init:
    build: 
      context: .
      dockerfile: init.Dockerfile

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: projeto-labbd
      POSTGRES_PORT: '5432'
      POSTGRES_HOST: postgres
    
    depends_on:
      postgres:
        condition: service_healthy
    
    volumes:
      - db_init_control:/.init_control
      
    networks:
      - postgres-relatorio

networks:
  postgres-relatorio:
    driver: bridge

volumes:
  postgres:
  db_init_control:

